name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out Secrets 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Your token is:${{ secrets.MY_SENSITIVE_TOKEN }}"   
