name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out security gate 🚀
on: [push]
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Check for password file
        run: |
          [ -f passwords.txt ] && exit 1 || exit 0
